module.exports = {
  authors: [
    {
      full_name: 'Ernest Hemingway',
      email: 'e-h@gmail.com',
      country: 'United States of America',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Edgar Allan Poe',
      email: 'e-a-p@gmail.com',
      country: 'United States of America',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Stephen King',
      email: 's-k@gmail.com',
      country: 'United States of America',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Theodore Dreiser',
      email: 't-d@gmail.com',
      country: 'United States of America',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Mark Twain',
      email: 'm-t@gmail.com',
      country: 'United States of America',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Francis Scott Fitzgerald',
      email: 'f-s-f@gmail.com',
      country: 'United States of America',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Jack London',
      email: 'j-l@gmail.com',
      country: 'United States of America',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Margaret Mitchell',
      email: 'm-m@gmail.com',
      country: 'United States of America',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'O Henry',
      email: 'o-h@gmail.com',
      country: 'United States of America',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Joanne Rowling',
      email: 'j-r@gmail.com',
      country: 'Great Britain',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'John Tolkien',
      email: 'j-t@gmail.com',
      country: 'Great Britain',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Robert Louis Stevenson',
      email: 'r-l-s@gmail.com',
      country: 'Great Britain',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Alexandre Dumas',
      email: 'a-d@gmail.com',
      country: 'France',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Jules Verne',
      email: 'j-v@gmail.com',
      country: 'France',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Stendal',
      email: 'stendal@gmail.com',
      country: 'France',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Honore de Balzac',
      email: 'h-d-b@gmail.com',
      country: 'France',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Guy de Maupassant',
      email: 'g-d-m@gmail.com',
      country: 'France',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
};
