module.exports = {
  authors: [
    {
      full_name: 'Ernest Hemingway',
      email: 'e-h@gmail.com',
      country: 'United States of America',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Edgar Allan Poe',
      email: 'e-a-p@gmail.com',
      country: 'United States of America',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Stephen King',
      email: 's-k@gmail.com',
      country: 'United States of America',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Theodore Dreiser',
      email: 't-d@gmail.com',
      country: 'United States of America',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Mark Twain',
      email: 'm-t@gmail.com',
      country: 'United States of America',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Francis Scott Fitzgerald',
      email: 'f-s-f@gmail.com',
      country: 'United States of America',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Jack London',
      email: 'j-l@gmail.com',
      country: 'United States of America',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Margaret Mitchell',
      email: 'm-m@gmail.com',
      country: 'United States of America',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'O Henry',
      email: 'o-h@gmail.com',
      country: 'United States of America',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Joanne Rowling',
      email: 'j-r@gmail.com',
      country: 'Great Britain',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'John Tolkien',
      email: 'j-t@gmail.com',
      country: 'Great Britain',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Robert Louis Stevenson',
      email: 'r-l-s@gmail.com',
      country: 'Great Britain',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Alexandre Dumas',
      email: 'a-d@gmail.com',
      country: 'France',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Jules Verne',
      email: 'j-v@gmail.com',
      country: 'France',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Stendal',
      email: 'stendal@gmail.com',
      country: 'France',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Honore de Balzac',
      email: 'h-d-b@gmail.com',
      country: 'France',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      full_name: 'Guy de Maupassant',
      email: 'g-d-m@gmail.com',
      country: 'France',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  genres: [
    {
      title: 'Criminal',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Drama',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Historical',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Science Fiction',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Fantazy',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Romance',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Biography',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Adventures',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Western',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Fairy Tells',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Miphology',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Education',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Detective',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Comedy',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Classic',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  countries: [
    {
      title: 'USA',
      description: 'United States of America',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'GB',
      description: 'Great Britain',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'UA',
      description: 'Ukraine',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'DE',
      description: 'Deutschland',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'FR',
      description: 'France',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'AUS',
      description: 'Australia',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'BEL',
      description: 'Belgium',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'BRA',
      description: 'Brazil',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'GE',
      description: 'Georgia',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'DK',
      description: 'Denmark',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'IL',
      description: 'Israel',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'IN',
      description: 'India',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'IE',
      description: 'Ireland',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'IT',
      description: 'Italy',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'CA',
      description: 'Canada',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'CN',
      description: 'China',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'KR',
      description: 'Korea',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'LV',
      description: 'Latvia',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'LT',
      description: 'Lithuania',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'NL',
      description: 'Netherlands',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'NO',
      description: 'Norway',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'PL',
      description: 'Poland',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'PT',
      description: 'Portugal',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'TR',
      description: 'Turkey',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'FI',
      description: 'Finland',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'CZ',
      description: 'Czech Republic',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'CH',
      description: 'Switzerland',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'EE',
      description: 'Estonia',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'JP',
      description: 'Japan',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'NZ',
      description: 'New Zealand',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'PUR',
      description: 'Puerto Rico',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'MLT',
      description: 'Malta',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'BEN',
      description: 'Benin',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'SWE',
      description: 'Sweden',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'RU',
      description: 'Russian',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'ISL',
      description: 'Iceland',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  shelves: [
    {
      title: 'Shelf #1',
      description: 'Fantazy, Science Fiction',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Shelf #2',
      description: 'Fairy Tells, Miphology',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Shelf #3',
      description: 'Adventures, Western',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Shelf #4',
      description: 'Biography, Historical',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Shelf #5',
      description: 'Romance, Drama',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Shelf #6',
      description: 'Criminal, Detective',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Shelf #7',
      description: 'Comedy, Education',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Shelf #8',
      description: 'Classic',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  customers: [
    {
      full_name: 'Jhon Doe',
      email: 'j-d@gmail.com',
      phone: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      password: 'awerty',
    },
    {
      full_name: 'Jhon Doe',
      email: 'j-d@gmail.com',
      phone: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      password: '$2b$10$6hfNBzmZCAXn37rYnc/rNOJaXcR4hSLbvxKpNE.dPT1kRPy5nQGBC',
    },
    {
      full_name: 'Mick Box',
      email: 'm-b.gmail.com',
      phone: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      password: 'qwerty',
    },
    {
      full_name: 'Freddie Mercury',
      email: 'f-m.gmail.com',
      phone: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      password: 'qwerty',
    },
    {
      full_name: 'David Bowie',
      email: 'd-b.gmail.com',
      phone: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      password: 'qwerty',
    },
    {
      full_name: 'Bill Gates',
      email: 'b-g.gmail.com',
      phone: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      password: 'qwerty',
    },
    {
      full_name: 'Steven Jobs',
      email: 's-b.gmail.com',
      phone: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      password: 'qwerty',
    },
    {
      full_name: 'Mike Tyson',
      email: 'm-t.gmail.com',
      phone: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      password: 'qwerty',
    },
    {
      full_name: 'Rocco Marchegiano',
      email: 'r-m.gmail.com',
      phone: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      password: 'qwerty',
    },
    {
      full_name: 'Vito Carleone',
      email: 'v-c.gmail.com',
      phone: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      password: 'qwerty',
    },
    {
      full_name: 'David Byron',
      email: 'g-b.gmail.com',
      phone: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      password: 'qwerty',
    },
  ],
  orders: [
    {
      title: 'Request #1000-4321',
      order_date: '2022-02-15',
      customer: 'Jhon Doe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Request #1000-4322',
      order_date: '2022-02-18',
      customer: 'Jhon Doe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Request #1000-4325',
      order_date: '2022-02-27',
      customer: 'David Bowie',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Request #1000-4326',
      order_date: '2022-03-02',
      customer: 'Bill Gates',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Request #1000-4327',
      order_date: '2022-03-08',
      customer: 'Steven Jobs',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Request #1000-4328',
      order_date: '2022-04-04',
      customer: 'Mike Tyson',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Request #1000-4329',
      order_date: '2022-05-01',
      customer: 'Rocco Marchegiano',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Request #1000-4330',
      order_date: '2022-02-27',
      customer: 'Rocco Marchegiano',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Request  #1000-4324',
      order_date: '2022-02-24',
      customer: 'Freddie Mercury',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Request #1000-4332',
      order_date: '2022-04-04',
      customer: 'Mike Tyson',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Request #1000-4333',
      order_date: '2022-04-04',
      customer: 'Mike Tyson',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Request #1000-4334',
      order_date: '2022-05-01',
      customer: 'Jhon Doe',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Rquest #1000-4335',
      order_date: '2022-03-02',
      customer: 'Bill Gates',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  books: [
    {
      title: 'Унесенные ветром',
      genre: 'Drama',
      shelf: 'Shelf #5',
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      image: null,
    },
    {
      title: 'Гарри Поттер',
      genre: 'Fantazy',
      shelf: 'Shelf #1',
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      image: null,
    },
    {
      title: 'Золотой жук',
      genre: 'Detective',
      shelf: 'Shelf #6',
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      image: null,
    },
    {
      title: 'Сияние',
      genre: 'Fairy Tells',
      shelf: 'Shelf #2',
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      image: null,
    },
    {
      title: 'Финансист',
      genre: 'Drama',
      shelf: 'Shelf #5',
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      image: null,
    },
    {
      title: 'Великий Гэтсби',
      genre: 'Drama',
      shelf: 'Shelf #5',
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      image: null,
    },
    {
      title: 'Морской волк',
      genre: 'Drama',
      shelf: 'Shelf #5',
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      image: null,
    },
    {
      title: 'Вождь краснокожих',
      genre: 'Comedy',
      shelf: 'Shelf #7',
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      image: null,
    },
    {
      title: 'Остров сокровищ',
      genre: 'Adventures',
      shelf: 'Shelf #3',
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      image: null,
    },
    {
      title: 'Сильмарилион',
      genre: 'Fantazy',
      shelf: 'Shelf #1',
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      image: '1698487194009 - browser-vs-node.png',
    },
    {
      title: 'JavaScript',
      genre: 'Education',
      shelf: 'Shelf #5',
      description: 'Book about JavaScript',
      createdAt: new Date(),
      updatedAt: new Date(),
      image: null,
    },
    {
      title: 'Чистый код',
      genre: 'Education',
      shelf: 'Shelf #7',
      description: 'Book about development',
      createdAt: new Date(),
      updatedAt: new Date(),
      image: null,
    },
    {
      title: 'Пармская обитель',
      genre: 'Drama',
      shelf: 'Shelf #5',
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      image: '1698566974676 - bom.png',
    },
    {
      title: 'Отец Горио',
      genre: 'Drama',
      shelf: 'Shelf #5',
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      image: null,
    },
    {
      title: 'Милый друг',
      genre: 'Drama',
      shelf: 'Shelf #5',
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      image: null,
    },
    {
      title: 'Приключения Тома Сойера',
      genre: 'Adventures',
      shelf: 'Shelf #3',
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      image: null,
    },
    {
      title: 'Прощай оружие',
      genre: 'Drama',
      shelf: 'Shelf #5',
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      image: null,
    },
  ],
};
